import './global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      {/* <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Quicksand&family=Roboto+Mono:wght@100;200;400;500;700&display=swap" rel="stylesheet"/>
      </head> */}
      <body>{children}</body>
    </html>
  )
}
