import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body >
        <header>
          <nav className='header-section'>
          <h2>DeMo</h2>
            <ul className='list-item'>
              
            <li><Link href="/home" className='link-item'> Home</Link></li>
           
            <li><Link href="/dashboard" className='link-item'> Dashboard</Link></li>
           
            <li><Link href="/about" className='link-item'>About</Link></li>
           
            </ul>
          </nav>
        </header>
        {children}</body>
    </html>
  )
}
